config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :boards do
    resources :bookings, shallow: true
  end

  resources :dishes

  get 'about', to: "about#index"
  get 'welcome/index'
  root 'welcome#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ActiveRecord::Base
  validates_presence_of :board_number, :board_seats, :floor

  has_many :bookings

  after_initialize :check_booking

  private


  # set table booking status to false if there is no bookings
  def check_booking
    if self.bookings.length == 0
      self.booked = false
    end
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :boards_ids, class_name: 'Board', foreign_key: :board_id

  validates_presence_of :email

  private

  # method to delete booking after 24 hours after it was created
  def delete_old_booking
    self.class.destroy(id)
  end
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  validates :description, :dish_price, :dish_name, presence: true

  has_one_attached :dish_photo

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :danger, :info, :warning, :success
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[show edit update destroy]

  def index
    @boards = Board.all
  end

  def show; end

  def new
    @board = Board.new
  end

  def edit; end

  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:board_number, :board_seats, :board_bookings, :booked, :floor)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  def index
    @bookings = Booking.all
  end

  def show; end

  def new
    @booking = Booking.new
    @board = Board.find(params[:board_id])
  end

  def edit; end

  def create
    @booking = Booking.new(booking_params)
    @board = Board.find(params[:board_id])
    @booking.board_id = @board.id

    respond_to do |format|
      if @booking.save
        BookingMailer.with(booking: @booking).booking_created.deliver_later
        BookingJob.set(wait_until: @booking.created_at < 24.hours.ago).perform_later(@booking)
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
        @board.booked = true
        @board.save!
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to board_bookings_path, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to board_bookings_url, notice: 'Booking was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:board_id, :booked_by, :booking_time, :email, :order_comment)
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[show edit update destroy]

  def index
    @dishes = Dish.all
  end

  def show; end

  def new
    @dish = Dish.new
  end

  def edit; end

  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_path, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_dish
    @dish = Dish.find(params[:id])
  end

  def dish_params
    params.require(:dish).permit(:dish_name, :dish_price, :dish_photo, :category, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<section class="info_main">
  <h2>We are ABC restaurant</h2>
</section>
<section id="about_main">
  At this restaurant we serve a best French cuisine with all the love our country can give to you
</section>

<div id="menu_info">
  <h2 class="h2_rest"> Restaurant </h2>
  <p> We work from 10:00 to 22:00 and provide food delivery </p>
  <%= link_to 'Check menu', dishes_path, class: 'btn_brand' %>
</div>
<img class="ratatouille_photo" src="<%= asset_url 'ratatouille-casserole.jpeg' %>"  alt="Ratatouille Photo">

<div id="history_info">
  <h2 class="h2-rest"> Book a table </h2>
  <p>You can book a table any time</p>
  <p>Except Sundays</p>
  <%= link_to 'Book table', boards_path, class: 'btn_brand' %>
</div>
<img class="creme" src="<%= asset_url 'creme.jpeg' %>" alt="Nicoise Photo">

<div id="map_info">
  <h2 class="h2-rest">You can find us here</h2>
  <div id="map"></div>
</div>

<style>
  #map {
      width: 300px;
      height: 200px;
  }
</style>

<!DOCTYPE html>
<head>
  <style>
    #map {
        width: 1300px;
        height: 700px;
    }
  </style>
</head>
<body>
<script>
  function initMap() {
      let abc_rest = {lat: 48.858057, lng: 2.288146};

      let map = new google.maps.Map(
          document.getElementById('map'), {zoom: 12, center: abc_rest, mapTypeControl: false, keyboardShortcuts: false}
      );

      let marker = new google.maps.Marker({position: abc_rest, map: map})

      google.maps.event.addListener(marker, 'click', function () {
          window.location.href = 'https://goo.gl/maps/s8Bu8oRFns1zSiGXA'
      })
  }
</script>
<script
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVz_MSburTLzuQ-kF4JVdslQTfnS20ZDw&callback=initMap&v=weekly"
  async
></script>
</body>

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <div class="field">
    <p>
      <%= form.label :board_number %>
    </p>
    <%= form.text_field :board_number %>
    <p>
      <%= form.label :board_seats %>
    </p>
    <%= form.text_field :board_seats %>
    <p>
      <%= form.label :floor %>
    </p>
    <%= form.number_field :floor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boards</h1>

 <div>
  <div id="first_floor">
    <% first_floor = Board.where(floor: 1) %>
    <% first_floor.each do |board| %>
      <tr>
        <p>
          Table places:
        <td><%= board.board_seats %></td>
        <% if board.booked? %>
          <h6 class="booked_table">Already booked</h6>
        <% else %>
          <div class="new_booking">
            <%= link_to 'Book a table', board %>
          </div>
        <% end %>
      </tr>
    <% end %>
  </div>

  <div id="second_floor">
    <tbody>
    <% second_floor = Board.where(floor: 2) %>
    <% second_floor.each do |board| %>
      <tr>
        <p>
          Table places:
        <td><%= board.board_seats %></td>
        <% if board.booked? %>
          <h6 class="booked_table">Already booked</h6>
        <% else %>
          <div class="new_booking">
            <%= link_to 'Book a table', board %>
          </div>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </div>

  <div id="third_floor">
    <tbody>
    <% third_floor = Board.where(floor: 3) %>
    <% third_floor.each do |board| %>
      <tr>
        <p>
        Table places:
        <td><%= board.board_seats %></td>
        <% if board.booked? %>
          <h6 class="booked_table">Already booked</h6>
          <% else %>
          <div class="new_booking">
            <%= link_to 'Book a table', board %>
          </div>
          <% end %>
      </tr>
    <% end %>
    </tbody>
  </div>
 </div>

<script>
  function select_floor(floor_id) {
      if(floor_id === 'floor1'){
          $("#first_floor").show();
          $("#second_floor").hide();
          $("#third_floor").hide();
      }
      if(floor_id === 'floor2'){
          $("#second_floor").show();
          $("#first_floor").hide();
          $("#third_floor").hide();
      }
      if(floor_id === 'floor3'){
          $("#third_floor").show();
          $("#second_floor").hide();
          $("#first_floor").hide();
      }
  }
</script>
<div id="floor_buttons">
  <button class="btn_floor" id="floor1" onclick="select_floor(this.id)">Floor 1</button>
  <button class="btn_floor" id="floor2" onclick="select_floor(this.id)">Floor 2</button>
  <button class="btn_floor" id="floor3" onclick="select_floor(this.id)">Floor 3</button>
</div>


<br>

<% if Date.tomorrow.strftime('%A') == 'Sunday' %>
<strong>We are closed on Sundays, sorry</strong>
  <% else %>
<%= link_to 'Back', root_path %>
<% end %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Board number:</strong>
  <%= @board.board_number %>
</p>
<p>
  <strong>Total seats: </strong>
    <%= @board.board_seats %>
</p>

<% if @board.booked == true %>
  <p>
    <strong>All bookings: </strong>
    <% @board.bookings.each do |x| %>
    <li><%= "Starts at #{x.booking_time}" %></li>
  <% end %>
  </p>
<% else %>
  <div class="new_booking">
    <%= link_to 'Book a table', new_board_booking_path(@board), remote: true %>
  </div>
<% end %>

<%= link_to 'Back', boards_path %>

app/views/bookings/_form.html.erb
<%= form_with(model: [@board, @booking.becomes(Booking)]) do |form| %>
  <div class="field">
    <p>
      <%= form.label :booked_by %>
    </p>
    <%= form.text_field :booked_by, placeholder: 'Enter your first and last name' %>
    <p>
      <%= form.label :booking_time%>
    </p>
    <% daytime = DaytimeService.new(@booking).create_workday(10, 22) %>
    <%= form.collection_select :booking_time, daytime, :to_s, :to_s, include_blank: false %>
    <p>
      <%= form.label :email %>
    </p>
    <%= form.text_field :email %>
    <p>
      Add comment?
      <input class="comment_check" type="checkbox" name="Add order comment" value="0" onchange="show_comment()">
    </p>
    <script>
      function show_comment () {
          if($('.comment_check').is(":checked"))
              $("#comment_box").show();
          else
              $("#comment_box").hide();
              $(".dish_box").hide();
              $(".menu_check").prop("checked", false)
      }
    </script>
    <div id="comment_box">
      <p>
        <%= form.label :order_comment %>
      </p>
      <%= form.text_field :order_comment, placeholder: 'Write comment to your order, if you have any' %>
      <p>
        Show menu?
        <input class="menu_check" type="checkbox" name="Add order comment" value="0" onchange="show_menu()">
      </p>
    </div>

    <div class="dish_box">
      <% all_dishes = Dish.all %>
      <% all_dishes.each do |dish| %>
        <div class="booked_images">
          <div class="book_dish_info">
            <%= dish.dish_name %>
            <p>Price: <%= dish.dish_price %>€</p>
          </div>
          <img class="book_dish_img" src="<%= url_for(dish.dish_photo) %>" alt="photo">
        </div>
      <% end %>
    </div>
    <script>
        function show_menu () {
            if($('.menu_check').is(":checked"))
                $(".dish_box").show();
            else
                $(".dish_box").hide();
        }
    </script>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking info</h1>

<%= render 'form', booking: @booking %>
<%= link_to 'Show', @booking %> |
<%= link_to 'Back', board_bookings_path(@board) %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
  <tr>
    <th>Booked table</th>
    <th>Booked by</th>
    <th>Booking time</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @bookings.each do |booking| %>
    <tr>
      <td><%= booking.board_id %></td>
      <td><%= booking.booked_by %></td>
      <td><%= booking.booking_time %></td>
      <td><%= link_to 'Show', booking %></td>
      <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
      <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_board_booking_path(@board) %>

app/views/bookings/new.html.erb
<h1>New Board</h1>

<%= render 'form', booking: @booking %>
<%= link_to 'Back', board_path(@board) %>

app/views/bookings/new.js.erb
$('.new_booking a').parent().html("<%= j render 'bookings/form' %>")

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Booked table number:</strong>
  <%= @booking.board_id %>
</p>
<p>
  <strong>Booked by: </strong>
  <%= @booking.booked_by %>
</p>
<p>
  <strong>Booked for: </strong>
  <%= @booking.booking_time %>
</p>
<% if @booking.order_comment.present? %>
  <p>
    <strong>Order comment: </strong>
    <%= @booking.order_comment %>
  </p>
<% end %>
<p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', boards_path %>

app/views/dishes/_dish.html.erb
<div class="dish_info">
  <h1><%= dish.dish_name %></h1>
  <p class="dish_desc"><%= dish.description %></p>
  <h2>Price: <%= dish.dish_price %>€</h2>
</div>
<div class="dish_photo">
  <img class="dish_img" src="<%= url_for(dish.dish_photo) %>" alt="photo">
</div>

app/views/dishes/_form.html.erb
<%= form_with(model: dish) do |form| %>
  <div class="field">
    <p>
      <%= form.label :dish_name %>
    </p>
    <%= form.text_field :dish_name %>
    <p>
      <%= form.label :dish_price%> in €
    </p>
    <%= form.number_field :dish_price %>
    <% category_list = %w[Alcohol Salad Soup Hot] %>
    <p>
      <%= form.label :category %>
    </p>
    <%= form.collection_select :category, category_list, :to_s, :to_s, include_blank: false %>
    <p>
      <%= form.label :description %>
    </p>
    <%= form.text_field :description %>
    <p>
      <%= form.label :dish_photo %>
    </p>
    <%= form.file_field :dish_photo %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish info</h1>

<%= render 'form', dish: @dish %>
<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path(@dish) %>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dishes</h1>

<table>
  <tbody>
  <div class="menu_list">
    <h1 class="category_name">Soups</h1>
    <% Dish.where(category: 'Soup').each do |dish| %>
      <%= render dish, dish: dish %>
    <% end %>

    <h1 class="category_name">Hot dishes</h1>
    <% Dish.where(category: 'Hot').each do |dish| %>
      <%= render dish, dish: dish %>
    <% end %>

    <h1 class="category_name">Salads</h1>
    <% Dish.where(category: 'Salad').each do |dish| %>
      <%= render dish, dish: dish %>
    <% end %>

    <h1 class="category_name">Alcohol</h1>
    <% Dish.where(category: 'Alcohol').each do |dish| %>
      <%= render dish, dish: dish %>
    <% end %>
  </div>
  </tbody>
</table>

<br>

app/views/dishes/new.html.erb
<h1>Add new dish</h1>

<%= render 'form', dish: @dish %>
<%= link_to 'Back', dishes_path(@dish) %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>The dish:</strong>
  <%= @dish.dish_name %>
</p>
<p>
  <strong>Price: </strong>
  <%= @dish.dish_price %>€
</p>
<p>
  <strong>Description:</strong>
  <%= @dish.description %>
</p>
<p>
  <strong>Photo: </strong>
  <img src="<%=(url_for(@dish.dish_photo)) %>" alt="photo">
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ABCrestaurant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="abc_header">
    <a class="logoLink" href="<%= root_path %>">
      <img class="abc_logo" src="<%= asset_url 'logo.png' %>"  alt="ABC Logo">
    </a>

<!--    <span style="float: right">-->
      <%= link_to 'Book a table', boards_path, class: "navButton" %>
      <%= link_to 'Menu', dishes_path, class: "navButton" %>
<!--    </span>-->
  </header>

  <body>
    <div class="container">
      <%= yield %>

    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><img src="<%= asset_url "logo.png" %>" alt="logo.png" height="100" width="100"> </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<style>
  body {
      background: url('<%= asset_url 'welcome_background.jpg' %>');
      background-size: cover;
  }
</style>
<img src="<%= asset_url 'welcome.png' %>" alt="Welcome" id="welcome_sign">
<%= link_to 'About us', about_path, class: "aboutButton"%>